age = input("How old are you? ")
print("On your next birthday you will be " + str(int(age) + 1) + ".")
print()
eggs = input("How many cartons of eggs do you have?")
print("You have " + str(int(eggs) * 12) + " eggs.")
print()
cookies = input("How many cookies do you have?")
people = input("How many people are there?")
print("Each person may have " + str(int(cookies) / int(people)) + " cookies.")